djangoApp04/lab04/lab04/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('votacion/', include('votacion.urls')),
    path('admin/', admin.site.urls),
]

djangoApp04/lab04/votacion/urls.py
from django.urls import path

from . import views

app_name = 'votacion'

urlpatterns = [
    path('',views.index,name='index'),
    path('<int:region_id>/',views.candidatos,name='candidatos'),
    path('<int:region_id>/detalles/',views.detalles,name='detalles'),

]

djangoApp04/lab04/votacion/models.py
from pyexpat import model
from django.db import models

# Create your models here.
class Region(models.Model):
    region = models.CharField(max_length=30)

class Candidato(models.Model):
    region = models.ForeignKey(Region,on_delete=models.CASCADE)
    nombre_candidato = models.CharField(max_length=40)
    apellido_candidato = models.CharField(max_length=40)
    profesion_candidato = models.CharField(max_length=30)

djangoApp04/lab04/votacion/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse


from .models import Region, Candidato

def index(request):
    regiones=Region.objects.all()
    context = {'regiones':regiones}
    return render(request,'index.html',context)

def candidatos(request,region_id):
    regionex = get_object_or_404(Region,pk =region_id)
    return render(request,'candidatos.html',{'regionex':regionex})

def detalles(request,region_id):
    candidato = get_object_or_404(Candidato,pk =region_id)
    return render(request,'detalles.html',{'candidato':candidato})
# Create your views here.

djangoApp04/lab04/votacion/templates/candidatos.html
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
   <title>Document</title>
</head>
<body>
   <div class="container">
      <br>
      <h1 class="text-center">Region:{{regionex.region}}</h1>
      <br>
      <div class="container">
         <div class="text-center"> 
            <h3>Candidatos</h3>
            <br>
            <table class="table table-random table-striped">
            {%for x in regionex.candidato_set.all %}
            <tr>
               <td>
                  <h4><a href="{% url 'votacion:detalles' x.id %}"><li>{{x.nombre_candidato}} {{x.apellido_candidato}}</a></h4>
               </td>
            </tr>   
            {% endfor %}
         </table>
         </div>
      </div>
   </div>
</body>
</html>

djangoApp04/lab04/votacion/templates/detalles.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <title>Document</title>
</head>
<body>
<div class="container">

<div class="text-center">
    <br>
    <h1>Datos personales del candidato</h1>

<div class="container">
    <div class="text-center">
<table class="table table-success table-striped">
<tr>
  
    <th>Nombre</th>
    <th>Apellido</th>
    <th>Profesion</th>
</tr>
<tr>
    <td>{{candidato.nombre_candidato}}</td>
    <td>{{candidato.apellido_candidato}}</td>
    <td>{{candidato.profesion_candidato}}</td>
</tr>
</table>
</div>
</div>   
</div>
</div>
</body>
</html>

djangoApp04/lab04/votacion/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <title>Document</title>
</head>
<body>
    <div class="container">
    <br>
    <h1 class="text-center">Votaciones Regionales</h1>
    <div class="container">
        <div class="text-center"> 
    {% if regiones %}
        {% for region in regiones %}
            <h3><a href="{{region.id}}/">{{region.region}}</a><br></h3>   
        {% endfor %}
    </div>
    {% else %}
        <p>No hay registros</p>
    {% endif %}
  </div>
</body>
</html>